CODE_ERROR = 400
CODE_SUCCESS = 200

TEXT_SUCCESS_REQUEST = "哈喽哈喽，当看到这句话的时候证明请求成功了～"
TEXT_COMMIT_CURRENT_POST_DATA = "提交正确的POST数据咯？"
TEXT_COMMIT_CURRENT_GET_DATA = "提交正确的GET数据咯？"
TEXT_COOKIES_IS_EMPTY = "你的Cookies是空的咧~"
TEXT_USING_POST = "我觉得你应该用POST来提交数据"
TEXT_CONNECT_TIMEOUT = "登陆超时了咧，稍后再试试？"
TEXT_TOKEN_ERROR = "我觉得你得先登陆，或者你的登陆过期了，重新登录试试？"
TEXT_TOKEN_INVALID = "请求成功了，但是Token无效，重新登录吧。"
TEXT_UNKNOW_ERROR = "糟了，碰到了未知错误，你可以看看data字段是否有数据～"
TEXT_FRESHMAN_INIT = "新生或专升本同学请在教务系统(syjw.wsyu.edu.cn)完善信息并审核且修改密码后再来这里试试吧～"
TEXT_STUNUM_OR_PASSWD_ERROR = "学号或者密码可能有点问题，要不你再检查一下？"
TEXT_STUPASS_DECRYPT_ERROR = "密码解密失败咧，联系一下开发者吧～"
TEXT_NETWORK_ERROR = "服务器网络有点问题，等会再试试吧，抱歉哈～"
TEXT_NETWORK_OR_COOKIES_ERROR = "服务器网络或cookies有问题，你再重新登录一下试试？"
TEXT_TRY_AGAIN = "再重新试试？"
TEXT_TRY_AGAIN_OR_COOKIES_ERROR = "再重新试试？或者服务器网络或cookies有点问题。"
TEXT_JWSYS_ERROR = "学校的教务系统挂掉了，请等待学校修复后再来看看吧～"
TEXT_HAS_BEEN_BANNED = "叮！你咋被封禁了！来找我问问吧～"
TEXT_NOCHANGE_ON_CLASS_NAME = "你的班级并没有发生啥变化咧"
TEXT_SUCCESS_CHANGE_CLASSNAME = "你已成功变更班级~"
TEXT_ERROR_STU_NUM = "请输入正确的11位学号或10位教工号咧，且暂不支持18位专升本账号（身份证号）登录。"
TEXT_NO_GRADE = "你暂时没有学业信息咧"
TEXT_LOGIN_FIRST = "你得先登陆兄弟"

