# Generated by Django 3.2.20 on 2023-07-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_work_inform'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_inform',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '正常作业'), (2, '一般提醒'), (3, '紧急通知'), (4, '紧急注意')], default=1, verbose_name='级别'),
        ),
    ]
