# Generated by Django 3.2.20 on 2023-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_work_inform_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='password',
            field=models.CharField(default=12345, max_length=32, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
