# Generated by Django 3.2.20 on 2023-07-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_stuinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='stuinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='stuinfo',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='name',
            field=models.CharField(max_length=16, verbose_name='网名'),
        ),
    ]
