# Generated by Django 3.2.20 on 2023-07-13 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230713_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuinfo',
            old_name='name',
            new_name='username',
        ),
    ]
