# Generated by Django 3.2.20 on 2023-07-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
