# Generated by Django 3.2.20 on 2023-07-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20230719_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_list',
            name='bedroom',
            field=models.CharField(default='418', max_length=32, verbose_name='寝室'),
        ),
    ]
