# Generated by Django 3.2.20 on 2023-07-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_class_list_bedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_list',
            name='QQID',
            field=models.CharField(max_length=64, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='class_list',
            name='bedroom',
            field=models.CharField(max_length=32, verbose_name='寝室'),
        ),
        migrations.AlterField(
            model_name='class_list',
            name='className',
            field=models.CharField(max_length=32, verbose_name='所在班级'),
        ),
        migrations.AlterField(
            model_name='class_list',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='class_list',
            name='phoneID',
            field=models.CharField(max_length=64, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='class_list',
            name='schoolID',
            field=models.CharField(max_length=64, verbose_name='学号'),
        ),
    ]
