# Generated by Django 3.2.20 on 2023-08-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230719_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SmallIntegerField(max_length=32, verbose_name='主题')),
                ('content', models.SmallIntegerField(max_length=128, verbose_name='内容')),
                ('place', models.SmallIntegerField(max_length=32, verbose_name='地点')),
                ('hold_time', models.DateField(verbose_name='举办时间')),
                ('img', models.FileField(max_length=128, upload_to='community/', verbose_name='Logo')),
                ('active', models.SmallIntegerField(choices=[(1, '社团招新'), (2, '举办活动'), (3, '志愿参与')], verbose_name='活动类型')),
            ],
        ),
    ]
