# Generated by Django 3.2.20 on 2023-08-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20230801_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityactive',
            name='content',
            field=models.CharField(max_length=128, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='communityactive',
            name='place',
            field=models.CharField(max_length=64, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='communityactive',
            name='title',
            field=models.CharField(max_length=64, verbose_name='主题'),
        ),
    ]
